D = {
"(Startabläufe),":"(start sequences),",
"(Startbewegungen Bild für Bild auswerten).":"(analyse your start frame by frame).",
"(deine Daten und Verläufe) und":"(your data and progress) and",
"+ Diese Einstellungen als Voreinstellung speichern":"+ Save these settings as a preset",
"Abbrechen":"Cancel",
"Ablauf vor dem Start":"Pre-start sequence",
"Absenden":"Send",
"Abstand zwischen Signalen":"Gap between signals",
"Aktuelle Messung als Ton-Bild-Versatz übernehmen":"Use current measurement as audio–video offset",
"Alle Daten löschen":"Delete all data",
"Als CSV kopieren":"Copy as CSV",
"An Land":"Dry-land",
"An Land:":"Dry-land:",
"Anderes Video wählen":"Choose another video",
"Auf Störsignal":"Reacted to a distractor",
"Auf der Tartanbahn":"On the track",
"Auf der Tartanbahn:":"On the track:",
"Aufnahme":"Recording",
"Auswertung":"Analysis",
"Bei einem Originalvideo trägst du 1 ein. Hast du eine iPhone-Zeitlupe als normales Video gespeichert, läuft sie langsamer ab. Dann trägst du den Faktor ein, z. B. 8, wenn 240 Bilder pro Sekunde mit 30 abgespielt werden.":"Enter 1 for an original video. If you saved an iPhone slow-motion clip as a normal video, it plays back slower. In that case enter the factor, e.g. 8 if 240 fps footage plays back at 30 fps.",
"Bereiche":"Sections",
"Bilder pro Sekunde":"Frames per second",
"Bis zum ersten Startsignal":"Until the first signal",
"Bitte beschreibe dein Anliegen kurz.":"Please briefly describe your request.",
"Bitte gib eine gültige E-Mail-Adresse ein, damit du eine Antwort bekommen kannst.":"Please enter a valid email address so we can reply.",
"Blockzeit (Take-off)":"Block time (take-off)",
"Damit springst du mit −1 / +1 genau ein Bild weiter.":"Makes −1 / +1 jump exactly one frame.",
"Das Kontaktformular wird gerade eingerichtet. Bitte versuche es später noch einmal.":"The contact form is still being set up. Please try again later.",
"Das Senden hat nicht geklappt. Prüfe deine Internetverbindung und versuche es noch einmal.":"Sending failed. Check your internet connection and try again.",
"Das Video ist zu kurz.":"The video is too short.",
"Das ist keine gültige Sicherung. Füge bitte den kompletten kopierten Text ein.":"That is not a valid backup. Please paste the complete copied text.",
"Daten":"Data",
"Dein Anliegen":"Your message",
"Deine Daten liegen nur in diesem Browser auf diesem Gerät. Mit „Sicherung kopieren“ und „Sicherung laden“ nimmst du sie auf ein anderes Gerät oder in eine andere Version der App mit. Die CSV-Daten kannst du in Excel oder R auswerten.":"Your data is stored only in this browser on this device. Use “Copy backup” and “Load backup” to move it to another device or another version of the app. You can analyse the CSV data in Excel or R.",
"Deine E-Mail-Adresse":"Your email address",
"Der Entwickler":"The developer",
"Die Anzahl der möglichen Störsignale. Das bedeutet nicht, dass genauso viele oder überhaupt welche ertönen.":"The maximum number of distractors. It does not mean that this many – or any at all – will sound.",
"Die Besonderheit: Mit Startz kannst du das auch alleine professionell umsetzen. Du bist nicht auf die Hilfe anderer angewiesen.":"What makes it special: with Startz you can train like a pro on your own – no starter or training partner needed.",
"Die Idee":"The idea",
"Diese Datei stammt nicht aus Startz.":"This file is not a Startz backup.",
"Direkt gemessen":"Measured directly",
"Du gehst zuerst ins Wasser und startest dann aus der Rückenstartposition. Das Ins-Wasser-Gehen ist im Startablauf enthalten.":"You enter the water first and start from the backstroke start position. Entering the water is part of the start sequence.",
"Du hast den Take-off noch nicht gesetzt.":"You haven't marked the take-off yet.",
"Du hast nicht getippt":"You didn't tap",
"Du hast nicht losgelassen":"You didn't release",
"Du hast noch keine Voreinstellung gespeichert. Sobald du alle Fragen beantwortet hast, kannst du deine Einstellungen unter dem Start-Button speichern.":"You haven't saved a preset yet. Once you've answered all questions, you can save your settings below the Start button.",
"Du springst vom Startblock ins Wasser.":"You dive from the starting block into the water.",
"Du startest aus dem Startblock auf der Bahn, mit dem kompletten Startablauf.":"You start from the blocks on the track with the full start procedure.",
"Du startest stehend vom Block, z. B. für Brust, Schmetterling und Freistil.":"You start standing on the block, e.g. for breaststroke, butterfly and freestyle.",
"Du tippst bei der Hupe auf den Bildschirm, und die App zeigt dir sofort deine Reaktionszeit.":"You tap the screen at the horn and the app shows your reaction time instantly.",
"Du tippst beim Startsignal auf den Bildschirm. Die App zeigt dir sofort deine Reaktionszeit.":"You tap the screen at the gun. The app shows your reaction time instantly.",
"Du trainierst nur deine Reaktion, z. B. im Sitzen. Dabei kannst du deine Reaktionszeit auch direkt messen.":"You train your reaction only, e.g. seated. You can also measure your reaction time directly.",
"Du warst zu früh":"False start – you went too early",
"Du übst trocken, z. B. im Sitzen oder mit Sprüngen.":"You practise on dry land, e.g. seated or with jumps.",
"Einheit löschen":"Delete session",
"Einheiten":"Sessions",
"Einzelstart":"Single start",
"Einzelstart oder Serie":"Single start or set",
"Einzelstart:":"Single start:",
"Ergebnis":"Result",
"Erklärung anzeigen":"Show explanation",
"Erweiterte Einstellungen":"Advanced settings",
"Erweiterte Einstellungen öffnen":"Open advanced settings",
"Es ertönt direkt das Startsignal.":"The starting signal sounds straight away.",
"Fertig":"Done",
"Füße verlassen den Block":"feet leave the block",
"Füße verlassen die Startblöcke":"feet leave the blocks",
"Geh in die Startblöcke":"Get into your blocks",
"Geh zu deinem Startblock":"Walk to your blocks",
"Geh zum Startblock":"Walk to the block",
"Geh ins Wasser":"Enter the water",
"Gelungen":"Good",
"Gesamt":"Overview",
"Gespeicherte Messungen":"Saved measurements",
"Hier speicherst du deine aktuellen Einstellungen unter einem Namen.":"Save your current settings under a name.",
"Hier triffst du die Voreinstellungen: Wo genau trainierst du? Wie startest du? Wie oft möchtest du starten?":"Set up your session here: Where are you training? How do you start? How many starts?",
"Hände lösen":"Hands off",
"Hände lösen hier":"Hands off here",
"Hüfte hoch":"Hips up",
"Ideal, wenn du die Zeit per Video auswerten möchtest oder während des Ablaufs nicht auf den Bildschirm drücken kannst.":"Ideal if you want to analyse your time on video or can't tap the screen during the sequence.",
"Im Training ist oft keine weitere Person da, die Startsignale geben kann. Startz übernimmt das: Die App spielt den Startablauf nach Wettkampfregeln ab, mit echtem Startsignal und zufälligen Zeitabständen. Störsignale trainieren zusätzlich deine Aufmerksamkeit.":"In training there is often nobody around to give start commands. Startz does it for you: the app plays the start procedure according to competition rules, with a real starting signal and randomised timing. Distractors also train your attention.",
"Im Wasser":"In the pool",
"Im Wasser:":"In the pool:",
"Info zu den Daten":"About the data",
"Info zu den Phasen":"About the phases",
"Info zu den Werten":"About the values",
"Info zum Ton-Bild-Versatz":"About the audio–video offset",
"Info zum Zeitlupen-Faktor":"About the slow-motion factor",
"Info zur Frage":"About this question",
"Info zur Videoauswertung":"About video analysis",
"Ja":"Yes",
"Ja, endgültig löschen":"Yes, delete permanently",
"Ja:":"Yes:",
"Kein Störsignal":"No distractor",
"Kontakt":"Contact",
"Kontaktieren":"Get in touch",
"Lautstärke":"Volume",
"Leg deine Hände auf":"Place your hands",
"Leg deine Hände hier auf":"Place your hands here",
"Leg deine Hände wieder auf, der Durchgang beginnt neu":"Place your hands again – the rep restarts",
"Lege das Zeitfenster fest, in dem nach dem Fertigmachen („Take your marks“) das erste Start- oder Störsignal ertönen soll.":"Set the time window after “Take your marks” in which the first starting signal or distractor sounds.",
"Lege das Zeitfenster fest, in dem nach „Set“ das erste Start- oder Störsignal ertönen soll. Standard sind 1,5–2,1 s: In internationalen Sprintfinals liegen im Mittel 1,78 s (± 0,16 s) zwischen „Set“ und Startschuss.":"Set the time window after “Set” in which the gun or the first distractor sounds. Default is 1.5–2.1 s: in international sprint finals the set-to-gun interval averages 1.78 s (± 0.16 s).",
"Lege ein Zeitfenster fest, in dem nach einem Störsignal das nächste Signal ertönen soll.":"Set the time window after a distractor in which the next signal sounds.",
"Lege eine feste Zeit oder ein Zeitfenster fest: Wie lange nach dem ersten kurzen Pfiff (Herantreten an den Startblock) soll das zweite Signal (auf den Startblock steigen) ertönen?":"Set a fixed time or a time window: how long after the short whistles (step up to the block) should the long whistle (step onto the block) sound?",
"Lege eine feste Zeit oder ein Zeitfenster fest: Wie lange nach dem ersten langen Pfiff (ins Wasser gehen) soll der zweite lange Pfiff (zurück an die Wand in die Startposition) ertönen?":"Set a fixed time or a time window: how long after the first long whistle (enter the water) should the second long whistle (return to the wall into the start position) sound?",
"Lege eine feste Zeit oder ein Zeitfenster fest: Wie lange nach dem zweiten langen Pfiff soll das Signal zum Fertigmachen („Take your marks“) ertönen?":"Set a fixed time or a time window: how long after the second long whistle should “Take your marks” sound?",
"Lege eine feste Zeit oder ein Zeitfenster fest: Wie lange nach „On your marks“ soll das Kommando „Set“ ertönen?":"Set a fixed time or a time window: how long after “On your marks” should the “Set” command sound?",
"Lege eine feste Zeit oder ein Zeitfenster fest: Wie lange, nachdem du auf den Startblock gestiegen bist, soll das Signal zum Fertigmachen („Take your marks“) ertönen?":"Set a fixed time or a time window: how long after you step onto the block should “Take your marks” sound?",
"Leichtathletik":"Athletics",
"Maximale Störsignale":"Maximum distractors",
"Messung":"Measurement",
"Messung löschen":"Delete measurement",
"Messung speichern":"Save measurement",
"Misslungen":"Poor",
"Mit Startz kannst du deine Reaktionszeit sportartspezifisch trainieren.":"With Startz you can train your reaction time in a sport-specific way.",
"Mit diesem Schalter wechselst du zwischen Schwimmen und Leichtathletik. Voreinstellungen und Auswertungen sind für beide Sportarten getrennt.":"Use this switch to change between swimming and athletics. Presets and analyses are kept separately for each sport.",
"Mit direkter Zeitmessung":"With timing",
"Mit direkter Zeitmessung:":"With timing:",
"Mit direkter Zeitmessung?":"Measure your reaction time?",
"Mit welcher Wahrscheinlichkeit statt des echten Startsignals zuerst ein Störsignal ertönt. Ist die Wahrscheinlichkeit zu hoch, erwartest du eher ein Störsignal. Ist sie zu niedrig, erwartest du eher das echte Startsignal.":"How likely it is that a distractor sounds before the real starting signal. Set it too high and you start expecting a distractor; too low and you start anticipating the real signal.",
"Möchtest du Störsignale einbauen?":"Add distractors?",
"Name der Voreinstellung":"Preset name",
"Name, z. B. Montag Sprint":"Name, e.g. Monday sprint",
"Nein":"No",
"Nein:":"No:",
"Nimm die Startposition ein und leg die Hände aufs Display":"Get into your start position and place your hands on the screen",
"Nochmal":"Again",
"Notiz zum Start":"Start notes",
"Nur die Reaktion":"Reaction only",
"Nur die Reaktion:":"Reaction only:",
"Oben wechselst du zwischen":"At the top you switch between",
"Ohne direkte Zeitmessung":"Without timing",
"Ohne direkte Zeitmessung:":"Without timing:",
"Okay":"OK",
"Passe die Lautstärke flexibel an. Teste sie mit den beiden Knöpfen darunter.":"Adjust the volume as needed. Test it with the two buttons below.",
"Pause":"Rest",
"Perfekt für einzelne Starts oder wenn du noch nicht weißt, wie viel Zeit du zwischen den Starts hast.":"Perfect for one-off starts or if you don't yet know how much time you'll have between starts.",
"Quelle":"Source",
"Reaktion hier":"Reaction here",
"Reaktionen auf Störsignale":"Reactions to distractors",
"Reaktionstraining":"Reaction training",
"Reaktionszeit":"Reaction time",
"Rücken":"Backstroke",
"Rückenstart":"Backstroke start",
"Rückenstart:":"Backstroke start:",
"Sauber":"Clean",
"Schließen":"Close",
"Schwimmen":"Swimming",
"Serie":"Set",
"Serie fertig":"Set complete",
"Serie:":"Set:",
"Sicherung kopieren":"Copy backup",
"Sicherung laden":"Load backup",
"Sicherungsdatei wählen":"Choose backup file",
"So viel Zeit hast du zwischen deinen Starts.":"Your time between starts.",
"Speichern":"Save",
"Sportart":"Sport",
"Start aus dem Block":"Block start",
"Start ins Wasser":"Dive start",
"Startbewegung aus Video":"Start analysis from video",
"Startest du einmal oder mehrmals?":"One start or several?",
"Startsignal":"Starting signal",
"Startz wurde von Lasse Dietrich entwickelt. Er studiert Sportwissenschaft an der Technischen Universität Darmstadt und schwimmt mit Schwerpunkt auf den Sprintstrecken im Freistil.":"Startz was developed by Lasse Dietrich. He studies sport science at the Technical University of Darmstadt and swims, specialising in the freestyle sprint events.",
"Steig auf den Block":"Step onto the block",
"Stelle ein, wie viel Zeit dir vom Starten in der App bis zum Kommando „On your marks“ bleibt.":"Set how much time you have between starting the app and the “On your marks” command.",
"Stelle ein, wie viel Zeit dir vom Starten in der App bis zum ersten Pfiff (Herantreten an den Startblock) bleibt.":"Set how much time you have between starting the app and the first whistle (step up to the block).",
"Stopp":"Stop",
"Störsignal":"Distractor",
"Störsignale":"Distractors",
"Störsignale einbauen?":"Add distractors?",
"Take-off hier":"Take-off here",
"Ton":"Sound",
"Ton-Bild-Versatz":"Audio–video offset",
"Tonspur. Antippen springt an diese Stelle.":"Audio track. Tap to jump to this point.",
"Tour durch die App starten":"Start the app tour",
"Training starten":"Start training",
"Trockensprung an Land":"Dry-land jump",
"Verlauf":"Progress",
"Video auswählen":"Choose video",
"Video-Messungen":"Video measurements",
"Videoauswertung":"Video analysis",
"Von oben":"Dive start",
"Von oben:":"Dive start:",
"Vor dem richtigen Startsignal können zufällig Störsignale ertönen, auf die du nicht reagieren darfst. Das fördert deine Aufmerksamkeitsfähigkeit.":"Random distractors may sound before the real starting signal – don't react to them. This trains your attention.",
"Voreinstellungen":"Presets",
"Vorlauf":"Lead-in",
"Wahrscheinlichkeit Störsignal":"Distractor probability",
"Was möchtest du mitteilen?":"What would you like to tell us?",
"Was war gut, was nicht? Z. B. Reaktion gut, Hüfte zu tief, Eintauchwinkel zu flach, neue Fußstellung getestet":"What went well, what didn't? E.g. good reaction, hips too low, entry angle too flat, tried a new foot position",
"Wenn du eine Anzahl von Starts mit einer festen Pause dazwischen einstellen willst.":"If you want a number of starts with a fixed rest in between.",
"Wie ist der Start gelungen":"How was the start?",
"Wie startest du?":"How do you start?",
"Wie trainierst du?":"How are you training?",
"Wie viele Störsignale möchtest du maximal haben?":"Maximum number of distractors?",
"Wie war dein Start?":"How was your start?",
"Wiederholungen":"Reps",
"Wo trainierst du?":"Where are you training?",
"Zeitlupen-Faktor":"Slow-motion factor",
"Zu früh":"Too early",
"Zu früh losgelassen":"Released too early",
"Zurück":"Back",
"Zurück an die Wand, nimm die Startposition ein":"Back to the wall, take your start position",
"erste Bewegung":"first movement",
"optional":"optional",
"name@beispiel.de":"name@example.com",
"Ø Hände lösen":"Ø hands off",
"Über Startz":"About Startz",
"Über Startz und den Entwickler":"About Startz and the developer",
"Über das Zahnrad öffnest du weitere Einstellungen. Hier kannst du die genauen Abläufe deines Starts anpassen.":"The gear icon opens more settings where you can fine-tune your start sequence.",
"Über diesen Button startest du die Tour jederzeit neu. Viel Erfolg beim Training!":"Use this button to restart the tour at any time. Enjoy your training!",
"Übernehmen":"Import",
"… oder die kopierte Sicherung hier einfügen":"… or paste the copied backup here",
"▶ Hupe probehören":"▶ Test horn",
"▶ Startschuss probehören":"▶ Test gun",
"▶ Störsignal probehören":"▶ Test distractor",
"Tartanbahn":"Track",
"Reaktion":"Reaction",
"Startblock":"Block",
"Halte still":"Hold still",
"Kurze Pfiffe":"Short whistles",
"Mach dich fertig":"Get ready",
"Langer Pfiff":"Long whistle",
"Verpasst":"Missed",
"Fehlstart":"False start",
"Wie möchtest du reagieren?":"How do you want to respond?",
"Hände":"Hands",
"Blockzeit":"Block time",
"Datum":"Date",
"Starts":"Starts",
"sauber":"clean",
"Fehler":"Errors",
"Starts gemessen":"Starts measured",
"Ø Reaktionszeit":"Ø reaction time",
"Bestwert":"Best",
"Streuung (SD)":"Variability (SD)",
"Fehlstarts":"False starts",
"Starts protokolliert":"Starts logged",
"Videos ausgewertet":"Videos analysed",
"Ø Blockzeit (Take-off)":"Ø block time (take-off)",
"Beste Blockzeit":"Best block time",
"Streuung Blockzeit":"Block time variability",
"Kopiert ✓":"Copied ✓",
"Gespeichert ✓":"Saved ✓",
"Text markiert, kopiere ihn bitte":"Text selected – please copy it",
"Wird gesendet …":"Sending …",
"Danke! Deine Nachricht wurde gesendet.":"Thank you! Your message has been sent.",
"Worum geht es?":"What's it about?",
"Weiter":"Next",
"Zur Tour":"Start tour",
"Beenden":"End",
"Drei Bereiche":"Three sections",
"Schwimmen oder Leichtathletik":"Swimming or athletics",
"Voreinstellung speichern":"Save preset",
"Ab zwei Werten siehst du hier deinen Verlauf.":"Your progress appears here once you have two values.",
"Du hast noch keine Einheiten gespeichert.":"You haven't saved any sessions yet.",
"Du hast noch keine Messungen gespeichert.":"You haven't saved any measurements yet.",
"Du hast auf ein Störsignal reagiert":"You reacted to a distractor",
"Verlauf: Ø Reaktionszeit je Einheit (ms)":"Progress: Ø reaction time per session (ms)",
"Verlauf: saubere Starts je Einheit":"Progress: clean starts per session",
"Verlauf: Blockzeit je Video (ms)":"Progress: block time per video (ms)",
"Sprache":"Language",
"Deutsch":"Deutsch",
"English":"English",
"Hupe automatisch finden":"Find horn automatically",
"Startschuss automatisch finden":"Find gun automatically",
"Hupe hier setzen":"Mark horn here",
"Startschuss hier setzen":"Mark gun here",
"Ohne Startblock":"Without blocks",
"Start":"Start",
"Video":"Video",
"Training":"Training",
"Tour":"Tour",
"Einzelstart":"Single start",
}
